<?php if (count($this->deals) == 0) { ?>
<div class="alert alert-info">Derzeit sind leider keine Deals verfügbar :-(</div>
<?php } else { ?>
    <div class="row">
    <?php for($i = 0; $i < count($this->deals); $i++) { $deal = $this->deals[$i] ?>
        <div style="float:left; margin: 10px 20px; width:250px; box-shadow: 0 0 1px 1px #CCC;">
            <div style="text-align: center; margin: 20px auto">
                <p><?php echo $deal->getProduct()->getName() ?><br />
                <?php echo $this->currencyFormat($deal->getPrice(), "EUR", "de_DE"); ?><br />
                nur noch <b><?php echo $deal->getProduct()->getStock() ?></b> Stück verfügbar!</p>
                <p><a href="<?php echo $this->url('zf-deals\checkout') ?>?id=<?php echo $deal->getDealId() ?>" class="btn">Jetzt kaufen!</a></p>
            </div>
        </div>
    <?php } ?>
<?php } ?>
</div>